# Google Cloud Build configuration for automatic deployment
steps:
  # Build and push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tapestry-sso-demo:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tapestry-sso-demo:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tapestry-sso-demo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tapestry-sso-demo:latest'
      - '--region'
      - 'us-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/tapestry-sso-demo:latest'
